### ISSUE TITLE
Clarification on intended use needed

### ISSUE THREAD

**Issue by markus-mohemian** [jimblue/grav-plugin-webpacker#1]
Hi Jim, I am having problems to get the plugin running or maybe I am getting something wrong. Unfortunately the readme does not say anything about how to use the plugin.
I installed the plugin via admin panel which works fine.

<img width="707" alt="screen shot 2018-03-18 at 08 49 27" src="https://user-images.githubusercontent.com/34025882/37563828-9c478544-2a89-11e8-976f-66ce9ed982a3.png">

Then I changed into the /user/plugins/webpacker folder and installed all dependencies by running `yarn run setup` All dependencies installed successfully. Then I tried to change into the boilerplate directory, installed all dependencies there `yarn run setup` and tried to start webpack `yarn run webpack:dev`

I only received this error message:
```
$ node webpack.config.js --mode=development
module.js:545
    throw err;
    ^

Error: Cannot find module 'grav-plugin-webpacker'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/markus/Sites/grav-admin/dist/user/plugins/webpacker/boilerplate/webpack.config.js:2:19)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c node webpack.config.js --mode=development
Directory: /Users/markus/Sites/grav-admin/dist/user/plugins/webpacker/boilerplate
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/markus/Sites/grav-admin/dist/user/plugins/webpacker/boilerplate/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Could you please update the readme with a section on how to use the plugin in development/production mode. 

Big Thanks in advance,

**Comment by jimblue** [comment]
Hi @markus-mohemian !

There is too many things to document and I don't have time actually but I'll do it asap.

While here is a quick start:
- first read each option tooltips in admin to better understand the plugin
- then choose your options (proxy setting can't be localhost as it's use by webpack)
- copy the content of boilerplate folder into your theme folder root
- add your assets un webpack-config.js
- use the custom twig function {{ webpacker('name_of_your_assets.css|js') }} to load assets in your theme. It's using Grav assets manager in backgorund so you can pass the same options. (loading, groups, defer, etc...)
- run yarn run setup
- run yarn run webpack (it will run in the mode you choose in admin but you can override a mode with the flag --mode)

Enjoy

**Comment by markus-mohemian** [comment]
Thanks for the info. I will look into the tips you provided.

**Comment by jimblue** [comment]
Hi @markus-mohemian,

Just added a [documentation](https://github.com/jimblue/grav-plugin-webpacker#webpacker-plugin-) ✨ !!
It's a first batch, a lot more need to be added, but's it's enough to start using webpacker.
Feedback or PR welcome.

Cheers

**Comment by sandoche** [comment]
I needed to add this dependency:
https://github.com/jimblue/grav-plugin-webpacker/pull/6

To fix the `Error: Cannot find module 'grav-plugin-webpacker'`

**Comment by jimblue** [comment]
@sandoche thanks to point this out!

I've just fix this in last release.

Cheers
