### ISSUE TITLE
Support for LESS files

### ISSUE THREAD

**Issue by woutgg** [jimblue/grav-plugin-webpacker#11]
First of all thanks for the plugin, I really liked it while playing around with it. Unfortunately I'm using LESS instead of SCSS which the setup does not support.

It would be very nice if this could be added; I might give a try myself if I find the time to dive into it.

**Comment by jimblue** [comment]
Hi!

I'll consider that if more people are asking for LESS.
But honestly, everybody is using SASS today, you should try 😄 !

Best
