### ISSUE TITLE
SCSS not loaded and don't trigger compiling

### ISSUE THREAD

**Issue by nkCreation** [jimblue/grav-plugin-webpacker#2]
Hi ! 

Thank you for the plugin, it's a really good job.
But the documentation is not clear enough. I'm trying to load a scss file via webpacker : 

src/scss/app.scss

I've added it to the web pack array config, as of app.js and a css file. When I modify the CSS file, webpack compile and everything works. The same for the JS one. But the SCSS does not trigger webpack.

The next problem is that I can't load the SCSS file into the website : I'm trying to load it with : 
         {{ webpacker('app.css') }}

const entryFiles = ['css/custom.css', 'scss/app.scss', 'js/app.js']

Thank you !
Niko.

**Comment by jimblue** [comment]
Hi @nkCreation,

As I can reproduce your problem I'll close this until you come back with more informations.

Thank you.
