### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by NMathar** [jimblue/grav-plugin-webpacker#4]
Hi btw realy good plugin for gravcms it made my dev life so much easier. 

1.) Did you know that devtools are not working if your extension is enabled? I run your plugin with proxy enabled. It looks like a quote mark error in parsed debug console 
`
phpdebugbar.addDataSet -> \"//localhost:3001"\n  \"PATH\"  
`
2.) I get an 
`
invalid config loglevel="notice"
`
after upgrade webpack is that from your plugin?

Best regards,

NMonst4

**Comment by jimblue** [comment]
Hi @NMonst4 !

Never encounter this error before, I'm gonna have look into this and let you know if I found something.

Thank you for your feedback!

**Comment by NMonst4** [comment]
Nice thank you.

**Comment by jimblue** [comment]
Can you install the last release confirm me I can close this issue please, thank you.
