### ISSUE TITLE
webpacker function cant import compiled scripts

### ISSUE THREAD

**Issue by peca021** [jimblue/grav-plugin-webpacker#8]
I use grav rocket theme with some custom es6 classes to test your plugin and my project has been successfully compiled. 

When i wanted to import compiled scripts and styling files in twig base layout nothing happens and i cant figure out why, I followed the instructions from your documentation on npm.js.

When i try do log webpacker to console from twig base layout via dump() i get null as result.

Here is my bottom block in base.html.twig

`{% block bottom %}`
    `{{ webpacker('main.js') }}`
    `{{ assets.js('bottom') }}`
`{% endblock %}`

Here is my user/config/plugins/webpacker.yaml

`enabled: true`
`mode: development`
`https: true`
`ssl_certs: true`
`tunnel: false`
`open_website: true`
`dev_browser: 'google chrome'`
`open_url: local`
`console_display:`
`  error: true`
`  warning: true`
`overlay_display:`
`  error: true`
`  warning: true`
`overlay_text_color: '#CCCCCC'`
`overlay_bg_color: '#1D1D26'`
`open_browsersyncui: true`
`open_bundleanalyzer: true`
`open_jarvis: true`
`os_notify: true`
`os_notify_sound: true`
`browsersync_notify: true`
`manifest: true`
`vendors: true`
`commons: true`
`dev_sourcemaps: cheap-module-eval-source-map`
`prod_sourcemaps: source-map`
`proxy: '//localhost:3001/'`

Do you maybe have any idea of what i'm doing wrong?

**Comment by jimblue** [comment]
I can't reproduce your bug...
